site_name: Web Security
pages:
- [index.md, Home]
- ['content/XSS/Overview.md', 'XSS', 'XSS']
- ['content/XSS/XSS-Cookie.md', 'XSS', 'Stealing Cookie With XSS']
- ['content/XSS/CSS-history-hack.md', 'XSS', 'CSS History Hack']
- ['content/XSS/XSS-Worm.md', 'XSS', 'XSS Worm']
- ['content/XSS/XSS-Defense.md', 'XSS', 'XSS Defense']
- ['content/Browser_Security/Same-Origin-Policy.md', 'Browser Security', 'Same Origin Policy']
- ['content/CSRF/csrf.md', 'CSRF', 'CSRF']
- [help.md, Help]
- [about.md, About]
theme: united
repo_url: https://github.com/acgotaku/WebSecurity
copyright: Copyright &copy; 2015, <a href="https://github.com/acgotaku/WebSecurity">CSS WebSecurity</a>.